name: Deploy tamagotchi-testnet to k8s

on:
  push:
    branches: ['master']
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
  KUBE_NAMESPACE: gear-dapps

jobs:
  wait-previous-run:
    runs-on: ubuntu-latest
    steps:
      - uses: mktcode/consecutive-workflow-action@v1 # please read security note
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  build-and-push-tamagotchi-image:
    runs-on: ubuntu-latest
    needs: [wait-previous-run]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the github container registry
        uses: docker/login-action@master
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Tamagotchi Docker image
        uses: docker/build-push-action@master
        with:
          file: frontend-testnet/Dockerfile
          context: frontend-testnet
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-testnet:latest
          build-args: |
            VITE_NODE_ADDRESS=${{ secrets.VITE_NODE_ADDRESS }}
            VITE_AUTH_API_ADDRESS=${{ secrets.VITE_AUTH_API_ADDRESS }}
            VITE_FT_ADDRES=${{ secrets.VITE_FT_ADDRES }}
            VITE_GAME_ADDRESS=${{ secrets.VITE_GAME_ADDRESS }}
            VITE_TESTNET_WEBSITE_ADDRESS=${{ secrets.VITE_TESTNET_WEBSITE_ADDRESS }}
            

  deploy-tamagotchi-k8s:
    needs: [build-and-push-tamagotchi-image]
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to k8s
        uses: sergeyfilyanin/kubectl-aws-eks@master
        with:
          args: rollout restart deployment tamagotchi-testnet -n $KUBE_NAMESPACE
